<?php require_once __DIR__ . '/layouts/header.php'; ?>
<?php require_once __DIR__ . '/layouts/navbar.php'; ?>
<?php require_once __DIR__ . '/layouts/sidebar.php'; ?>
<section class="content">
    <!-- Banner Section with improved styling -->
    <div class="banner">
        <div class="banner-content">
            <h2>Special Offer!</h2>
            <p>Get 20% off on all drinks today. Don't miss out on this amazing deal!</p>
            <button class="cta-button">Order Now</button>
        </div>
        <div class="banner-decoration">
            <img src="/assets/image/logo/logo.png" alt="Decoration" class="banner-image">
        </div>
    </div>

    <!-- Booking Container -->
    <div class="booking-container">
        <!-- Booking Filters -->
        <div class="booking-filters">
            <div class="filter-tabs">
                <button class="filter-tab active" data-status="all">All Orders</button>
                <button class="filter-tab" data-status="processing">Processing</button>
                <button class="filter-tab" data-status="completed">Completed</button>
                <button class="filter-tab" data-status="cancelled">Cancelled</button>
            </div>
            <div class="search-filter">
                <input type="text" id="bookingSearch" placeholder="Search by order number...">
                <i class="fas fa-search"></i>
            </div>
        </div>

        <!-- Bookings List -->
        <div class="bookings-list">
            <!-- Booking cards will be dynamically generated by JavaScript -->
        </div>
    </div>
</section>


<!-- Add custom CSS for improved styling -->
<style>
    .banner {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background: linear-gradient(135deg, #ff5e62 0%, #ff9966 100%);
        border-radius: 10px;
        padding: 30px;
        margin-bottom: 30px;
        color: white;
        box-shadow: 0 5px 15px rgba(255, 94, 98, 0.3);
        overflow: hidden;
        position: relative;
    }
    
    .banner::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: url("data:image/svg+xml,%3Csvg width='100' height='100' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M11 18c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zm48 25c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zm-43-7c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zm63 31c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zM34 90c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zm56-76c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zM12 86c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm28-65c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm23-11c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm-6 60c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm29 22c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zM32 63c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm57-13c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm-9-21c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM60 91c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM35 41c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM12 60c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2z' fill='rgba(255,255,255,.1)' fill-rule='evenodd'/%3E%3C/svg%3E");
        opacity: 0.3;
    }
    
    .banner-content {
        flex: 1;
        z-index: 1;
    }
    
    .banner h2 {
        font-size: 28px;
        margin: 0 0 10px;
        font-weight: 700;
        text-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    
    .banner p {
        font-size: 16px;
        margin: 0 0 20px;
        max-width: 500px;
        opacity: 0.9;
    }
    
    .banner-decoration {
        position: relative;
        width: 150px;
        height: 150px;
        margin-left: 20px;
        z-index: 1;
    }
    
    .banner-image {
        width: 100%;
        height: 100%;
        object-fit: contain;
        filter: drop-shadow(0 5px 10px rgba(0, 0, 0, 0.2));
        animation: float 3s ease-in-out infinite;
    }
    
    @keyframes float {
        0% { transform: translateY(0px); }
        50% { transform: translateY(-10px); }
        100% { transform: translateY(0px); }
    }
    
    .cta-button {
        background-color: white;
        color: #ff5e62;
        border: none;
        border-radius: 5px;
        padding: 12px 25px;
        font-size: 16px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.3s ease;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    }
    
    .cta-button:hover {
        transform: translateY(-3px);
        box-shadow: 0 6px 15px rgba(0, 0, 0, 0.15);
    }
    
    .booking-filters {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
        flex-wrap: wrap;
        gap: 15px;
    }
    
    .filter-tabs {
        display: flex;
        gap: 10px;
        flex-wrap: wrap;
    }
    
    .filter-tab {
        background-color: #f5f5f5;
        border: none;
        border-radius: 5px;
        padding: 10px 15px;
        font-size: 14px;
        color: #666;
        cursor: pointer;
        transition: all 0.3s ease;
    }
    
    .filter-tab:hover {
        background-color: #e5e5e5;
    }
    
    .filter-tab.active {
        background-color: #ff5e62;
        color: white;
        box-shadow: 0 3px 8px rgba(255, 94, 98, 0.3);
    }
    
    .search-filter {
        position: relative;
        width: 250px;
    }
    
    .search-filter input {
        width: 100%;
        padding: 10px 15px 10px 40px;
        border: 1px solid #ddd;
        border-radius: 5px;
        font-size: 14px;
        transition: all 0.3s ease;
    }
    
    .search-filter input:focus {
        border-color: #ff5e62;
        box-shadow: 0 0 0 3px rgba(255, 94, 98, 0.1);
        outline: none;
    }
    
    .search-filter i {
        position: absolute;
        left: 15px;
        top: 50%;
        transform: translateY(-50%);
        color: #999;
    }
    
    @media (max-width: 768px) {
        .banner {
            flex-direction: column;
            text-align: center;
            padding: 20px;
        }
        
        .banner-decoration {
            margin: 20px 0 0;
        }
        
        .booking-filters {
            flex-direction: column;
            align-items: stretch;
        }
        
        .search-filter {
            width: 100%;
        }
    }
</style>
<link rel="stylesheet" href="/assets/css/booking.css">
<script src="/assets/js/booking.js"></script>
<?php require_once __DIR__ . '/layouts/footer.php'; ?>
